### ISSUE TITLE
Skip link in Figma

### ISSUE THREAD

**Issue by Robbert** [nl-design-system/backlog#187] opened 2023-04-27 13:07 UTC
Based on [Utrecht Skip Link](https://nl-design-system.github.io/utrecht/storybook/?path=/docs/css-skip-link--default-story) design tokens.

Interactive state:

- [ ] Normal
- [ ] Focus

**Comment by Yolijn** [comment] 2023-08-04 12:16
Duplicate of #74

**Closed by Yolijn** 2023-08-04 12:16 UTC
Labels: duplicate, designer toolkit
